language: r

r_packages:
  - covr

cache: packages

r:
  - oldrel
  - release
  - devel

matrix:
  allow_failures:
      - r: devel

dist: bionic

# Be strict when checking our package
warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'
